# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# react-native-permissions
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported
prepare_react_native_project!
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'

setup_permissions([
  'LocationWhenInUse',
  'LocationAlways',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SportFund' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    stable_modulemaps = [
      {
        build: '${PODS_CONFIGURATION_BUILD_DIR}/AsyncStorage/AsyncStorage.modulemap',
        public: '${PODS_ROOT}/Headers/Public/AsyncStorage/AsyncStorage.modulemap',
        public_headers_dir: File.join(__dir__, 'Pods', 'Headers', 'Public', 'AsyncStorage'),
        support_dir: File.join(__dir__, 'Pods', 'Target Support Files', 'AsyncStorage'),
        modulemap: 'AsyncStorage.modulemap',
        umbrella: 'AsyncStorage-umbrella.h',
      },
      {
        build: '${PODS_CONFIGURATION_BUILD_DIR}/RCTSwiftUI/RCTSwiftUI.modulemap',
        public: '${PODS_ROOT}/Headers/Public/RCTSwiftUI/RCTSwiftUI.modulemap',
        public_headers_dir: File.join(__dir__, 'Pods', 'Headers', 'Public', 'RCTSwiftUI'),
        support_dir: File.join(__dir__, 'Pods', 'Target Support Files', 'RCTSwiftUI'),
        modulemap: 'RCTSwiftUI.modulemap',
        umbrella: 'RCTSwiftUI-umbrella.h',
      },
      {
        build: '${PODS_CONFIGURATION_BUILD_DIR}/RNScreens/RNScreens.modulemap',
        public: '${PODS_ROOT}/Headers/Public/RNScreens/RNScreens.modulemap',
        public_headers_dir: File.join(__dir__, 'Pods', 'Headers', 'Public', 'RNScreens'),
        support_dir: File.join(__dir__, 'Pods', 'Target Support Files', 'RNScreens'),
        modulemap: 'RNScreens.modulemap',
        umbrella: 'RNScreens-umbrella.h',
      },
      {
        build: '${PODS_CONFIGURATION_BUILD_DIR}/react-native-geolocation-service/react_native_geolocation_service.modulemap',
        public: '${PODS_ROOT}/Headers/Public/react_native_geolocation_service/react-native-geolocation-service.modulemap',
        public_headers_dir: File.join(__dir__, 'Pods', 'Headers', 'Public', 'react_native_geolocation_service'),
        support_dir: File.join(__dir__, 'Pods', 'Target Support Files', 'react-native-geolocation-service'),
        modulemap: 'react-native-geolocation-service.modulemap',
        umbrella: 'react-native-geolocation-service-umbrella.h',
      },
    ]

    Dir.glob(File.join(__dir__, 'Pods', 'Target Support Files', '**', '*.xcconfig')).each do |xcconfig_path|
      contents = File.read(xcconfig_path)
      updated_contents = contents.dup

      stable_modulemaps.each do |modulemap|
        updated_contents.gsub!(modulemap[:build], modulemap[:public])
      end

      next if updated_contents == contents

      File.write(xcconfig_path, updated_contents)
    end

    stable_modulemaps.each do |modulemap|
      FileUtils.mkdir_p(modulemap[:public_headers_dir])
      FileUtils.rm_f(File.join(modulemap[:public_headers_dir], modulemap[:modulemap]))
      FileUtils.rm_f(File.join(modulemap[:public_headers_dir], modulemap[:umbrella]))
      FileUtils.cp(
        File.join(modulemap[:support_dir], modulemap[:modulemap]),
        File.join(modulemap[:public_headers_dir], modulemap[:modulemap])
      )
      FileUtils.cp(
        File.join(modulemap[:support_dir], modulemap[:umbrella]),
        File.join(modulemap[:public_headers_dir], modulemap[:umbrella])
      )
    end

    react_native_version = JSON.parse(
      File.read(File.join(__dir__, '..', 'node_modules', 'react-native', 'package.json'))
    )['version']
    rncore_artifacts_dir = File.join(__dir__, 'Pods', 'ReactNativeCore-artifacts')
    rncore_debug_tarball = File.join(rncore_artifacts_dir, "reactnative-core-#{react_native_version}-debug.tar.gz")
    rncore_release_tarball = File.join(rncore_artifacts_dir, "reactnative-core-#{react_native_version}-release.tar.gz")
    rncore_debug_tarball_url = "https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/#{react_native_version}/react-native-artifacts-#{react_native_version}-reactnative-core-debug.tar.gz"
    rncore_prebuilt_dir = File.join(__dir__, 'Pods', 'React-Core-prebuilt')
    rncore_simulator_binary = File.join(
      rncore_prebuilt_dir,
      'React.xcframework',
      'ios-arm64_x86_64-simulator',
      'React.framework',
      'React'
    )

    if !File.exist?(rncore_simulator_binary) && File.exist?(rncore_release_tarball)
      FileUtils.mkdir_p(rncore_artifacts_dir)
      unless File.exist?(rncore_debug_tarball)
        system('curl', '-L', rncore_debug_tarball_url, '-o', rncore_debug_tarball) ||
          raise('Failed to download React-Core-prebuilt debug tarball')
      end

      FileUtils.rm_rf(rncore_prebuilt_dir)
      FileUtils.mkdir_p(rncore_prebuilt_dir)
      system('tar', '-xf', rncore_debug_tarball, '-C', rncore_prebuilt_dir) || raise('Failed to extract React-Core-prebuilt debug tarball')
      File.write(File.join(rncore_prebuilt_dir, '.last_build_configuration'), 'Debug')
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        if target.name == 'RCTSwiftUIWrapper'
          build_config.build_settings['HEADER_SEARCH_PATHS'] = [
            build_config.build_settings['HEADER_SEARCH_PATHS'],
            '"${PODS_CONFIGURATION_BUILD_DIR}/RCTSwiftUI/Swift Compatibility Header"',
          ].compact.join(' ')
        end
      end
    end

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |build_config|
          build_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
        end
      end

      aggregate_target.user_project.save
    end
  end
end
